version: '3.8'
services:
  client:
    container_name: foodapp_client
    build:
      context: ./foodapp_client/
      target: dev

    volumes:
      - ./foodapp_client/:/src
    command: npm run react-scripts start
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DEBUG: foodapp_client:*
      
  webapi:
    build:
      context: ./webapi/
      target: dev

    depends_on:
      - db
    volumes:
      - ./webapi/:/src
    command: npm run start:dev
    ports:
      - "3030:3030"
    environment:
      NODE_ENV: development
      DEBUG: webapi:*

  db:
    image: pickapp/mariadb-alpine
    container_name: foodapp_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"    
    environment:
      MYSQL_ROOT_PASSWORD: ivoof7chaeP9ra8o
    volumes:
      - ../db/data:/var/lib/mysql          


