version: '3.8'

services:     
  webapi:
    networks:
      foodapp_net:
        aliases:
          - webapi_host
    build:
      context: ./
      target: dev

    depends_on:
      - db
    volumes:
      - .:/src
    command: npm run start:dev
    ports:
      - "3030:3030"
    environment:
      NODE_ENV: development
      DEBUG: webapi:*

  db:
    networks:
      foodapp_net:
        aliases:
          - db_host
    image: pickapp/mariadb-alpine
    container_name: foodapp_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"    
    environment:
      MYSQL_ROOT_PASSWORD: ivoof7chaeP9ra8o
    volumes:
      - ../db/data:/var/lib/mysql          

networks:
    foodapp_net:
      driver: bridge
