version: '3.8'

services:     

  db:
    networks:
      foodapp_net:
        aliases:
          - db_host
    image: pickapp/mariadb-alpine
    container_name: foodapp_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"    
    environment:
      MYSQL_ROOT_PASSWORD: ivoof7chaeP9ra8o
    volumes:
      - ../db/data:/var/lib/mysql          

networks:
    foodapp_net:
      driver: bridge
